name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with: 
            fetch_depth: 0
      - name: Sonarcloud Scan
        uses: sonarsource/SonarCloud@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with: 
          args: >
              -Dsonar.organization=AdilUPirwani
              -Dsonar.projectkey=GithubActionDemo
              -Dsonar.python.coverage.reportPaths=coverage.xml
