name: SonarCloud
on:
  workflow_dispatch:
    inputs:
      codecoveragetool:
        type: choice
        description: Code Coverage Tool
        required: true
        default: dotnet-coverage
        options:
          - dotnet-coverage
          - dotCover
          - coverlet
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  SonarQube-Example:
    name: SonarQube Setup Example
    runs-on: windows-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v3
        with: 
            fetch_depth: 0
      - name: Set code coverage tool output
        id: code-coverage-tool
        run: |
          CODE_COVERAGE_TOOL_NAME=${{ github.event.inputs.codecoveragetool }}
          echo "value=${CODE_COVERAGE_TOOL_NAME:-"dotnet-coverage"}" >> $GITHUB_OUTPUT
     
